const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Audio.Acts.StopAll
	];
};
self.C3_JsPropNameTable = [
	{Sprite: 0},
	{Sprite2: 0},
	{Solid: 0},
	{Physics: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Mouse: 0},
	{Audio: 0},
	{Lv1: 0},
	{Lv2: 0},
	{Lv3: 0},
	{Lv4: 0},
	{Lv5: 0},
	{Lv6: 0},
	{Lv7: 0},
	{Lv8: 0},
	{Lv9: 0},
	{score: 0},
	{Sprite5: 0},
	{Text: 0},
	{Level: 0},
	{cooldown: 0},
	{Cursor: 0},
	{Sprite6: 0},
	{Sprite7: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Lv1: class extends self.ISpriteInstance {},
	Lv2: class extends self.ISpriteInstance {},
	Lv3: class extends self.ISpriteInstance {},
	Lv4: class extends self.ISpriteInstance {},
	Lv5: class extends self.ISpriteInstance {},
	Lv6: class extends self.ISpriteInstance {},
	Lv7: class extends self.ISpriteInstance {},
	Lv8: class extends self.ISpriteInstance {},
	Lv9: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Cursor: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {}
}